### ISSUE TITLE
Company Index page - Argument #1 ($value) must be of type Countable

### ISSUE THREAD

**Issue by GewoonJaap** [LordChunk/Project-Agile#146]
## Describe the bug
When going to the company index page (**logged in as an admin**) you will get the following error: `count(): Argument #1 ($value) must be of type Countable|array, Illuminate\Database\Eloquent\Relations\HasMany given`

## To Reproduce
1. Login as an admin
2. Go to the company index page
3. Observe

## Expected behavior
The company index page should be displayed, just like it does when you are logged in on a non admin account.

## Screenshots
![image](https://user-images.githubusercontent.com/33700526/120917018-3d98d480-c6ad-11eb-9ffc-08fc1670d17d.png)

**Comment by LordChunk** [comment]
Deze bug is waarschijnlijk al ergens een keer gefixt, want ik kan 'm niet reproduceren.

**Comment by GewoonJaap** [comment]
Ja klopt. er is wel een leuke nieuwe voor in de plaats gekomen haha
