### ISSUE TITLE
Project Index - Class not found

### ISSUE THREAD

**Issue by GewoonJaap** [LordChunk/Project-Agile#147]
## Describe the bug
When logged in as admin, you can't open the project index page, you get the following error: `Class "App\Models\Projectgroup" not found (View: /app/resources/views/project/index.blade.php)`

## To Reproduce
1. Log in as admin
2. Go to project index page
3. Observe

## Expected behavior
There shouldn't be an error

## Screenshots
![image](https://user-images.githubusercontent.com/33700526/120924058-156f9c80-c6d2-11eb-8321-63fe4ed8c7b9.png)

**Comment by Nyekyoo** [comment]
@GewoonJaap I can't seem to reproduce this bug inside of development right now. Can you confirm that this is not an issue anymore?

**Comment by GewoonJaap** [comment]
@Nyekyoo Je zou even op een Linux build moeten testen, gezien deze fout niet op Windows is.

**Comment by Nyekyoo** [comment]
@GewoonJaap Op een Linux build is de error voor mij en @marijnkieboom ook niet reproduceerbaar.
