### ISSUE TITLE
Company Index - Call to undefined method App\Models\company_contact::getName()

### ISSUE THREAD

**Issue by GewoonJaap** [LordChunk/Project-Agile#176]
## Describe the bug
Wanneer een bedrijf een persoon gekoppeld heeft, kan je niet meer naar de index pagina, als **admin**

## To Reproduce
1. Login op het admin account
2. Bekijk details van een bedrijf
2. Voeg een contactpersoon toe
3. Ga naar de index pagina
4. Observe

## Expected behavior
Pagina zou gewoon moeten laden

## Screenshots
![image](https://user-images.githubusercontent.com/33700526/122384454-ff809800-cf6b-11eb-89e3-db8e302dba68.png)

**Comment by LordChunk** [comment]
Ik krijg deze niet gereproduced
